# Generated by Django 5.2.8 on 2025-11-22 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "avg_buy_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "last_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="portfolio.portfolio",
                    ),
                ),
            ],
        ),
    ]
