# Generated by Django 5.2.8 on 2025-11-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="avg_buy_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="stock",
            name="last_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="stock",
            name="symbol",
            field=models.CharField(max_length=20),
        ),
    ]
